### PR TITLE
Fix safe private method calls

### PR DESCRIPTION
**Pull request by marshall-lee**
Related to #140

### CODE REVIEW

**Comment by marshall-lee** [comment]
It should be merged only if #140 is a false alarm. Otherwise it should be fixed differently

**Comment by dblock** [comment]
So the problem was private methods? I feel like an error that the method is private is almost better than exposing private methods automatically. What do you think?

Either way this needs a CHANGELOG entry, please.

**Comment by marshall-lee** [comment]
@dblock 

It seems like exposing private methods was intented.
Look at the current [`delegate_attribute` implementation](https://github.com/intridea/grape-entity/blob/35ada1ebbd0659cd7686b7b21796a51b6bf1a6e2/lib/grape_entity/entity.rb#L572)

It checks that object responds to attribute name using `object.respond_to?(name, true)` (not just `object.respond_to?(name)` and evaluates it by `object.send(name)` (not by `object.public_send(name)`).

So this PR just makes safe and unsafe exposures behave identical because now only public methods can exposed when using `:safe` option.

As for me I don't like exposing private methods. If you think that only public methods should be exposed I could open a separate PR for this too. But it probably can be considered as a breaking change. Is it acceptable here?

**Comment by dblock** [comment]
Ok I am with you on this one @marshall-lee. Lets call it a bug and add a line to CHANGELOG please (via `--amend`) that says  something like "Fix: expose works with private methods".

**Pull request closed without merging**
