### PR TITLE
Bump version to 0.5.0

### PR DESCRIPTION
**Pull request by marshall-lee**
#151 introduces some breaking API changes so they go to 0.5.0.
I think nothing should be cut from the changes before so it's time to release 0.4.6 as is.

Also, tag `v0.4.6` should be added for 8af8074.

### CODE REVIEW

**Comment by dblock** [comment]
@marshall-lee For trivial things like this feel free to just commit/push.

**Comment by marshall-lee** [comment]
@dblock I'm not a collaborator yet. Thanks.

**Comment by dblock** [comment]
Ah yeah, cc: @mbleigh who said he'll add you, I don't have admin rights :(

**Comment by marshall-lee** [comment]
v0.4.6 is pushed to rubygems.

**Comment by dblock** [comment]
Nice work @marshall-lee! Thanks.

**Pull request merged**
